TutorAid/urls.py
from django.urls import path

from TutorAid import views

app_name = 'TutorAid'
urlpatterns = [
    path('', views.home_view, name='home'),

    path('courses', views.courses_view, name='courses'),
    path('courses/new', views.course_create_view, name='course_create'),

    path('course/<int:pk>/detail', views.course_detail_view, name='course_detail'),
    path('course/<int:pk>/update', views.course_update_view, name='course_update'),
    path('course/<int:pk>/delete', views.course_delete_view, name='course_delete'),

    path('course/<int:pk>/registration/new', views.registration_create_view, name='registration_create'),
    path('course/<int:pk>/registration/<int:registration_id>/delete', views.registration_delete_view, name='registration_delete'),

    path('course/<int:course_id>/session/new', views.session_create_view, name='session_create'),
    path('session/<int:session_id>/create-attendance', views.attendance_create_view, name='attendance_create'),
    path('session/<int:session_id>/update-attendance', views.attendance_update_view, name='attendance_update'),

    path('students', views.students_view, name='students'),
    path('students/new', views.student_create_view, name='student_create'),
    path('student/<int:pk>/detail', views.student_detail_view, name='student_detail'),
    path('student/<int:pk>/update', views.student_update_view, name='student_update'),
    path('student/<int:pk>/delete', views.student_delete_view, name='student_delete'),

    path('sessions', views.sessions_view, name='sessions'),

    path('invoices', views.invoices_view, name='invoices'),
    path('invoices/create-monthly-invoices', views.invoices_create_view, name='invoices_create'),
    path('invoice/<int:pk>', views.invoice_detail_view, name='invoice_detail'),
    path('invoice/<int:pk>/approve', views.invoice_approve_view, name='invoice_approve'),

]

project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('TutorAid/', include('TutorAid.urls')),
    path('admin/', admin.site.urls),
]

TutorAid/models.py
from django.db import models

class Course(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=20)
    lesson = models.CharField(max_length=10)
    module = models.CharField(max_length=10)
    fee_per_hour_per_student = models.IntegerField()

    def __str__(self):
        return self.name + "|" + self.lesson + "|" + self.module
    @property
    def get_id(self):
        return self.id
    @property
    def get_name(self):
        return self.name

    class Meta:
        db_table = 'course'

class Student(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=20)
    contact = models.CharField(max_length=10)
    school = models.CharField(max_length=10)

    def __str__(self):
        return self.name + "|" + self.school + "|" + self.contact
    @property
    def get_id(self):
        return self.id
    @property
    def get_name(self):
        return self.name

    class Meta:
        db_table = 'student'

class Registration(models.Model):
    id = models.AutoField(primary_key=True)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    student = models.ForeignKey(Student, on_delete=models.CASCADE)

    class Meta:
        db_table = 'registration'

class Session(models.Model):
    id = models.AutoField(primary_key=True)
    created_at = models.DateTimeField(auto_now_add=True)
    duration = models.IntegerField()
    course = models.ForeignKey(Course, on_delete=models.CASCADE)

    @property
    def get_id(self):
        return self.id
    @property
    def get_name(self):
        return self.course_id.__str__()

    class Meta:
        db_table = 'session'

class Attendance(models.Model):
    id = models.AutoField(primary_key=True)
    created_at = models.DateTimeField(auto_now_add=True)
    session = models.ForeignKey(Session, on_delete=models.CASCADE)
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    status = models.CharField(max_length=30)

    @property
    def get_session(self):
        return self.session_id.get_name
    @property
    def get_student(self):
        return self.student_id.__str__()

    class Meta:
        db_table = 'attendance'

class Invoice(models.Model):
    id = models.AutoField(primary_key=True)
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    year = models.IntegerField()
    month = models.IntegerField()
    invoiced_at = models.DateField(auto_now_add=True)
    charge = models.FloatField()
    is_payed = models.BooleanField(default=False)

    def __str__(self):
        return "{} - {}/{}|{}".format(self.student, self.year, self.month, self.charge)

    class Meta:
        db_table = 'invoice'

TutorAid/forms.py
from django import forms
from django.contrib.auth.models import User
from TutorAid import models

#Course
lesson_choices=(('Private', 'Private'), ('Group','Group'))
module_choices=(('IB1', 'IB1'), ('IB2','IB2'), ('SAT', 'SAT'))

class CourseForm(forms.ModelForm):
    class Meta:
        model=models.Course
        lesson=forms.ChoiceField(choices=lesson_choices)
        module=forms.ChoiceField(choices=module_choices)
        fields=['name','lesson','module','fee_per_hour_per_student']

#Student
class StudentForm(forms.ModelForm):
    class Meta:
        model=models.Student
        fields=['name','contact','school']

#Registration
class RegistrationForm(forms.Form):
    def __init__(self, queryset, *args, **kwargs):
        super(RegistrationForm, self).__init__(*args, **kwargs)
        self.fields['students'] = forms.ModelMultipleChoiceField(widget = forms.CheckboxSelectMultiple, queryset=queryset)

#Session
class SessionForm(forms.Form):
    duration = forms.IntegerField()

#Attendance
presence_choices=(('Present','Present'),('Absent','Absent'),('Absent by Prior Notice(0%)', 'Absent by Prior Notice(0%)'),('Absent by Late Notice(50%)','Absent by Late Notice(50%)'))
class AttendanceForm(forms.Form):
    status = forms.ChoiceField(choices=presence_choices)

AttendanceFormSet = forms.formset_factory(AttendanceForm, extra=0)

TutorAid/views.py
from itertools import groupby

from django.db.models import QuerySet
from django.http import HttpResponse
from django.http import Http404
from django.http import HttpResponseRedirect

from django.urls import reverse
from django.views import generic
from django.contrib.auth.models import Group

from django.db.models import Sum, F, Value

from django.template import loader
from django.shortcuts import get_object_or_404, render, redirect

from .models import Course, Student, Registration, Session, Attendance, Invoice
from . import forms
from datetime import datetime, timedelta


def home_view(request):
    return render(request, 'TutorAid/home.html')


def courses_view(request):
    courses = Course.objects.all()
    return render(request, 'TutorAid/courses.html', {'courses': courses})


def course_create_view(request):
    form = forms.CourseForm()
    if request.method == 'POST':
        form = forms.CourseForm(request.POST)
        if form.is_valid():
            course = form.save()
            course.save()
            return HttpResponseRedirect(reverse('TutorAid:courses'))
    return render(request, 'TutorAid/course_create.html', {'form': form})


def course_detail_view(request, pk):
    course = Course.objects.get(id=pk)
    registrations = course.registration_set.select_related('student')
    registered_students = [registration.student for registration in registrations]
    course_sessions = Session.objects.all().filter(course_id=pk)

    return render(request, 'TutorAid/course_detail.html',
                  {'course': course, 'registrations': registrations, 'course_sessions': course_sessions})


def course_update_view(request, pk):
    course = Course.objects.get(id=pk)
    form = forms.CourseForm(instance=course)
    if request.method == 'POST':
        form = forms.CourseForm(request.POST, instance=course)
        if form.is_valid():
            form.save()
            return redirect(reverse('TutorAid:course_detail', kwargs={'pk': pk}), )
    return render(request, 'TutorAid/course_update.html', {'form': form, 'course': course})


def course_delete_view(request, pk):
    course = Course.objects.get(id=pk)
    course.delete()
    return redirect(reverse('TutorAid:courses'))


def registration_create_view(request, pk):
    course = Course.objects.get(id=pk)
    registrations = course.registration_set.select_related('student')
    registered_students = course.registration_set.values('student_id').all()
    registrationForm = forms.RegistrationForm(Student.objects.all().exclude(id__in=registered_students))
    if request.method == 'POST':
        form = forms.RegistrationForm(Student.objects, request.POST)
        if form.is_valid():
            Students = form.cleaned_data.get('students')
            for i in range(len(Students)):
                RegistrationModel = Registration()
                RegistrationModel.course_id = pk
                RegistrationModel.student_id = Students[i].id
                RegistrationModel.save()
            return HttpResponseRedirect(reverse('TutorAid:course_detail', args=[pk]))
    return render(request, 'TutorAid/registration_create.html',
                  {'form': registrationForm, 'course': course, 'registered_students': registrations})


def registration_delete_view(request, pk, registration_id):
    registration = Registration.objects.get(id=registration_id)
    registration.delete()
    return redirect(reverse('TutorAid:course_detail', args=[pk]))


def session_create_view(request, course_id):
    course = Course.objects.get(id=course_id)
    course_sessions = Session.objects.all().filter(course_id=course_id)
    form = forms.SessionForm()
    if request.method == 'POST':
        form = forms.SessionForm(request.POST)
        if form.is_valid():
            SessionModel = Session()
            SessionModel.course_id = course_id
            SessionModel.duration = form.cleaned_data.get('duration')
            SessionModel.save()
            return redirect(reverse('TutorAid:attendance_create', args=[SessionModel.id]))
    return render(request, 'TutorAid/session_create.html',
                  {'form': form, 'course': course, 'course_sessions': course_sessions})


def attendance_create_view(request, session_id):
    session = Session.objects.get(id=session_id)
    students = [registration.student for registration in session.course.registration_set.order_by('id')]
    initial_values = [{'status': 'Present'} for _ in students]
    formset = forms.AttendanceFormSet(initial=initial_values)
    if request.method == 'POST':
        formset = forms.AttendanceFormSet(request.POST, initial=initial_values)
        if formset.is_valid():
            for student, form in zip(students, formset):
                AttendanceModel = Attendance()
                AttendanceModel.session = session
                AttendanceModel.student = student
                AttendanceModel.status = form.cleaned_data['status']
                AttendanceModel.save()
        return redirect(reverse('TutorAid:course_detail', args=[session.course.get_id]))
    return render(request, 'TutorAid/attendance_create.html',
                  {'attendance_data': zip(students, formset), 'formset': formset})


def attendance_update_view(request, session_id):
    session = Session.objects.get(id=session_id)
    attendances = session.attendance_set.order_by('id')
    students = list(map(lambda x: x.student, attendances))
    initial_values = [{'status': attendance.status} for attendance in attendances]
    formset = forms.AttendanceFormSet(initial=initial_values)
    if request.method == 'POST':
        formset = forms.AttendanceFormSet(request.POST, initial=initial_values)
        if formset.is_valid():
            for attendance, form in zip(attendances, formset):
                attendance.status = form.cleaned_data['status']
                attendance.save()
        return redirect(reverse('TutorAid:course_detail', args=[session.course.get_id]))
    return render(request, 'TutorAid/attendance_update.html',
                  {'attendance_data': zip(students, formset), 'formset': formset})


def students_view(request):
    students = Student.objects.all()
    return render(request, 'TutorAid/students.html', {'students': students})


def student_create_view(request):
    form = forms.StudentForm()
    if request.method == 'POST':
        form = forms.StudentForm(request.POST)
        if form.is_valid():
            student = form.save()
            student.save()
            return HttpResponseRedirect(reverse('TutorAid:students'))
    return render(request, 'TutorAid/student_create.html', {'form': form})


def student_detail_view(request, pk):
    student = Student.objects.get(id=pk)
    registrations = Registration.objects.all().filter(student_id=pk).values("course_id")
    registered_courses = Course.objects.all().filter(id__in=registrations)
    invoices = Invoice.objects.all().filter(student_id=pk)

    return render(request, 'TutorAid/student_detail.html',
                  {'student': student, 'registered_courses': registered_courses, 'invoices': invoices})


def student_update_view(request, pk):
    student = Student.objects.get(id=pk)
    form = forms.StudentForm(instance=student)
    if request.method == 'POST':
        form = forms.StudentForm(request.POST, instance=student)
        if form.is_valid():
            form.save()
            return redirect(reverse('TutorAid:student_detail', kwargs={'pk': pk}))
    return render(request, 'TutorAid/student_update.html', {'form': form, 'student': student})


def student_delete_view(request, pk):
    student = Student.objects.get(id=pk)
    student.delete()
    return redirect(reverse('TutorAid:students'))


def sessions_view(request):
    sessions = Session.objects.all()
    return render(request, 'TutorAid/sessions.html', {'sessions': sessions})


def invoices_view(request):
    invoices = Invoice.objects.select_related('student').order_by('-year', '-month')
    return render(request, 'TutorAid/invoices.html', {'invoices': invoices})


def invoices_create_view(request):
    today = datetime.today()
    current_month = today.replace(month=today.month + 1, day=1, hour=0, minute=0, microsecond=0)
    last_day_of_prev_month = current_month - timedelta(days=1)
    start_day_of_prev_month = current_month - timedelta(days=last_day_of_prev_month.day)
    atts = Attendance \
        .objects \
        .select_related('session__course', 'student') \
        .filter(created_at__gte=start_day_of_prev_month, created_at__lt=last_day_of_prev_month) \
        .order_by('student__name')
    atts_by_student = groupby(atts, lambda att: att.student)

    for student, atts in atts_by_student:

        def calc_att_rate(att: Attendance):
            if att.status == 'Absent by Prior Notice(0%)':
                return 0
            if att.status == 'Absent by Late Notice(50%)':
                return 0.5
            return 1

        fee = sum(
            map(lambda att: calc_att_rate(att) * att.session.duration * att.session.course.fee_per_hour_per_student,
                atts))

        invoice = Invoice()
        invoice.student = student
        invoice.charge = fee
        invoice.year = last_day_of_prev_month.year
        invoice.month = last_day_of_prev_month.month
        invoice.save()

    return redirect(reverse('TutorAid:invoices'))


def invoice_detail_view(request, pk):
    invoice = Invoice.objects.get(id=pk)
    invoice_month = datetime(year=invoice.year, month=invoice.month + 1, day=1, hour=0, minute=0, microsecond=0)
    last_day_of_prev_month = invoice_month - timedelta(days=1)
    start_day_of_prev_month = invoice_month - timedelta(days=last_day_of_prev_month.day)
    atts = Attendance.objects.select_related('session__course').filter(student=invoice.student).filter(
        created_at__gte=start_day_of_prev_month,
        created_at__lt=last_day_of_prev_month).order_by(
        'created_at')

    def calc_attr_rate(att: Attendance):

templates/TutorAid/attendance_create.html
{% extends 'TutorAid/base_template.html' %}

{% block content %}

    <head>

        <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet"
              id="bootstrap-css">
        <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
        <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>

        <style media="screen">
            a:link {
                text-decoration: none;
            }

            .row {
                margin: 100px;
            }

            .btnSubmit {
                border: none;
                border-radius: 1.5rem;
                padding: 1%;
                width: 20%;
                cursor: pointer;
                background: #0062cc;
                color: #fff;
            }
        </style>

    </head>

    <div class="container">

        <h3>Take Attendance</h3>

        <br>
        <br>

        <form action="" method="POST">
            {% csrf_token %}
            {{ formset.management_form }}
            <table class="table table-hover" id="attendance-table">
                <thead>
                <tr>
                    <th>Student Name</th>
                    <th>Attendance</th>
                </tr>
                </thead>
                {% for student, formset in attendance_data %}
                    <tr>
                        <td>{{ student.get_name }}</td>
                        <td>{{ formset.as_p }}</td>
                    </tr>
                {% endfor %}
            </table>
            <input type="submit" class="btnSubmit" value="Submit Attendance">
        </form>

    </div>

{% endblock content %}

templates/TutorAid/attendance_update.html
{% extends 'TutorAid/base_template.html' %}
{% load widget_tweaks %}

{% block content %}

    <head>

        <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet"
              id="bootstrap-css">
        <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
        <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>

        <style media="screen">
            a:link {
                text-decoration: none;
            }

            .row {
                margin: 100px;
            }

            .btnSubmit {
                border: none;
                border-radius: 1.5rem;
                padding: 1%;
                width: 20%;
                cursor: pointer;
                background: #0062cc;
                color: #fff;
            }
        </style>

    </head>

    <div class="container">

        <h3>Attendance</h3>

        <br>
        <br>

        <form action="" method="POST">
            {% csrf_token %}
            {{ formset.management_form }}
            <table class="table table-hover" id="attendance-table">
                <thead>
                <tr>
                    <th>Student Name</th>
                    <th>Attendance</th>
                </tr>
                </thead>
                {% for student, formset in attendance_data %}
                    <tr>
                        <td>{{ student.get_name }}</td>
                        <td>{{ formset.as_p }}</td>
                    </tr>
                {% endfor %}
            </table>
            <br>
            <input type="submit" class="btnSubmit" value="Update Attendance">
        </form>


    </div>

{% endblock content %}

templates/TutorAid/course_create.html
{% extends 'TutorAid/base_template.html' %}

{% block content %}

<head>

  <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
  <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
  <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>

  <style media="screen">
    a:link {
      text-decoration: none;
    }
    h6{
      text-align:center;
    }
  </style>

</head>

<div class="container">

            <h2 style="margin-left: 50px">Create New Course</h2>

        <br>
        <br>

        <form action="" method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <br>
            <input type="submit" value="Create new course">
        </form>

</div>

{% endblock content %}

templates/TutorAid/course_update.html
{% extends 'TutorAid/base_template.html' %}

{% block content %}

    <head>

        <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet"
              id="bootstrap-css">
        <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
        <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>

        <style media="screen">
            a:link {
                text-decoration: none;
            }

            h6 {
                text-align: center;
            }

            .row {
                margin: 100px;
            }

            .btnSubmit {
                border: none;
                border-radius: 1.5rem;
                padding: 1%;
                width: 20%;
                cursor: pointer;
                background: #0062cc;
                color: #fff;
            }
        </style>

    </head>

    <div class="container">

        <h3>Update course</h3>

        <br>
        <br>

        <form action="" method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" class="btnSubmit" value="Update">

        </form>


    </div>

{% endblock content %}

templates/TutorAid/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Main Page</title>
</head>
<body>

</body>
</html>

templates/TutorAid/invoices.html
{% extends 'TutorAid/base_template.html' %}

{% block content %}

    <head>

        <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet"
              id="bootstrap-css">
        <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
        <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>

        <style media="screen">
            a:link {
                text-decoration: none;
            }

            h6 {
                text-align: center;
            }

            .row {
                margin: 50px;
            }

            .heading {
                display: flex;
                justify-content: space-between;
            }
        </style>

    </head>

    <div class="container">

        <div class="heading">
            <h2 style="margin-left: 50px">Invoices</h2>
            <div class="create-button" style="margin-right: 50px; margin-top:20px;">
                <a class="btn btn-primary btn-lg" href="{% url 'TutorAid:invoices_create' %}"><span
                        class="glyphicon glyphicon-plus"></span>Create Monthly Invoices</a>
            </div>
        </div>

        <div class="row">

            <div class="panel panel-primary">
                <table class="table table-hover" id="dev-table" style="text-align:center;">
                    <thead>
                    <tr>
                        <th style="text-align:center;">Invoice</th>
                        <th style="text-align:center;">Total</th>
                        <th style="text-align:center;">Paid(Y/N)</th>
                        <th></th>
                    </tr>
                    </thead>
                    {% for invoice in invoices %}
                        <tr>
                            <td>
                                <a href="{% url 'TutorAid:invoice_detail' invoice.id %}">{{ invoice.year }}/{{ invoice.month }}
                                    - {{ invoice.student.name }}</a></td>
                            <td>{{ invoice.charge }}</td>
                            <td>{% if invoice.is_payed %} Y {% else %} N {% endif %}</td>
                            <td><a href="{% url 'TutorAid:invoice_approve' invoice.id %}">Approve payment</a></td>

                        </tr>
                    {% endfor %}
                </table>
            </div>


        </div>
    </div>


{% endblock content %}

templates/TutorAid/sessions.html
{% extends 'TutorAid/base_template.html' %}

{% block content %}

    <head>

        <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet"
              id="bootstrap-css">
        <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
        <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>

        <style media="screen">
            a:link {
                text-decoration: none;
            }

            h6 {
                text-align: center;
            }

            .row {
                margin: 50px;
            }
        </style>

    </head>

    <div class="container">

        <div>
            <h2 style="margin-left: 30px; margin-bottom: 20px;">Sessions/Attendances</h2>

            <div class="row">
                <table class="table table-hover" id="session-table">
                    <thead>
                    <tr>
                        <th>Session Time</th>
                        <th>Session Duration</th>
                        <th>Attendance</th>
                    </tr>
                    </thead>
                    {% for session in sessions %}
                        <tr>
                            <td>{{ session.created_at }}</td>
                            <td>{{ session.duration }} hour(s)</td>
                            <td><a href="{% url 'TutorAid:attendance_update' session.id %}">Attendance</a></td>
                        </tr>
                    {% endfor %}
                </table>
            </div>

        </div>

    </div>


{% endblock content %}

templates/TutorAid/student_detail.html
{% extends 'TutorAid/base_template.html' %}

{% block content %}

    <head>

        <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet"
              id="bootstrap-css">
        <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
        <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>

        <style media="screen">
            a:link {
                text-decoration: none;
            }

            h6 {
                text-align: center;
            }

            .row {
                margin: 50px;
            }
        </style>

    </head>

    <div class="container">

        <h2 style="margin-left: 50px">Student Details</h2>
        <div class="row">
            <div>
                <div style="display: inline">
                    <h4 style="display: inline">Student Info</h4>
                    <a class="btn btn-primary btn-xs" href="{% url 'TutorAid:student_update' student.id %}"><span
                            class="glyphicon glyphicon-edit"></span>Update</a>
                    <a class="btn btn-danger btn-xs" href="{% url 'TutorAid:student_delete' student.id %}"><span
                            class="glyphicon glyphicon-trash"></span>Delete</a>
                </div>
                <div>
                    Name: {{ student.name }}<br>
                    Contact: {{ student.contact }}<br>
                    School: {{ student.school }}<br>
                </div>

            </div>

            <br>
            <br>

            <div>
                <h4>Registered Courses</h4>

                <table class="table table-hover" id="student-table">
                    <thead>
                    <tr>
                        <th>Name</th>
                        <th>Lesson</th>
                        <th>Module</th>
                    </tr>
                    </thead>
                    {% for course in registered_courses %}
                        <tr>
                            <td><a href="{% url 'TutorAid:course_detail' course.id %}">{{ course.name }}</a></td>
                            <td>{{ course.lesson }}</td>
                            <td>{{ course.module }}</td>
                        </tr>
                    {% endfor %}

                </table>
                <p>you can only register for courses from Courses Page</p>

            </div>

            <br>
            <br>

            <div>
                <h4>Invoice</h4>

                <table class="table table-hover" id="invoice-table">
                    <thead>
                    <tr>
                        <th>Year-Month</th>
                        <th>charge</th>
                        <th>Payed</th>
                    </tr>
                    </thead>
                    {% for invoice in invoices %}
                        <tr>
                            <td><a href="{% url 'TutorAid:invoice_detail' invoice.id %}">{{ invoice.year }}/{{ invoice.month }}
                                - {{ invoice.student.name }}</a></td>
                            <td>{{ invoice.charge }}</td>
                            <td>{% if invoice.is_payed %} <p>YES</p> {% else %} <p>NO</p> {% endif %}</td>
                        </tr>
                    {% endfor %}
                </table>
            </div>

            <br>
            <br>
            <br>
        </div>
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

    </div>

{% endblock content %}

templates/TutorAid/students.html
{% extends 'TutorAid/base_template.html' %}

{% block content %}

    <head>

        <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet"
              id="bootstrap-css">
        <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
        <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>

        <style media="screen">
            a:link {
                text-decoration: none;
            }

            h6 {
                text-align: center;
            }

            .row {
                margin: 50px;
            }

            .heading {
                display: flex;
                justify-content: space-between;
            }
        </style>

    </head>

    <div class="container">
    <div class="heading">
        <h2 style="margin-left: 50px">Students</h2>
        <div class="create-button" style="margin-right: 50px; margin-top:20px;">
            <a class="btn btn-primary btn-lg" href="{% url 'TutorAid:student_create' %}"><span
                    class="glyphicon glyphicon-plus"></span>Create Student</a>
        </div>
    </div>

        <div class="row">

            <div class="panel panel-primary">
                <table class="table table-hover" id="dev-table" style="text-align:center;">
                    <tr>
                        <th style="text-align:center;">Student_id</th>
                        <th style="text-align:center;">Name</th>
                        <th style="text-align:center;">Contact</th>
                        <th style="text-align:center;">School</th>
                    </tr>
                    </thead>
                    {% for student in students %}
                        <tr>
                            <td><a href="{% url 'TutorAid:student_detail' student.id %}">{{ student.name }}</a></td>
                            <td>{{ student.name }}</td>
                            <td>{{ student.contact }}</td>
                            <td>{{ student.school }}</td>
                        </tr>
                    {% endfor %}
                </table>
            </div>


        </div>
    </div>


{% endblock content %}